### ISSUE TITLE
现处于安全模式

### ISSUE THREAD

**Issue by XingYeDianXia** [MicroCBer/BetterNCM#157]
更新1.0正式版后插件报错，提示进入安全模式并关闭所有插件。
错误记录如下：

第 1 次加载发生错误：
Error: 插件脚本 C:/betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20068), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18215)
    at v (betterncm://betterncm/framework.js:1:20106)
    at async r (betterncm://betterncm/framework.js:1:20390)
    at v (betterncm://betterncm/framework.js:1:20174)
    at async r (betterncm://betterncm/framework.js:1:20390)

第 2 次加载发生错误：
Error: 插件脚本 C:/betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20068), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18215)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at v (betterncm://betterncm/framework.js:1:20106)
    at async r (betterncm://betterncm/framework.js:1:20390)
    at v (betterncm://betterncm/framework.js:1:20174)
    at async r (betterncm://betterncm/framework.js:1:20390)

第 3 次加载发生错误：
Error: 插件脚本 C:/betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20068), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18215)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at v (betterncm://betterncm/framework.js:1:20106)
    at async r (betterncm://betterncm/framework.js:1:20390)
    at v (betterncm://betterncm/framework.js:1:20174)
    at async r (betterncm://betterncm/framework.js:1:20390)

**Comment by XingYeDianXia** [comment]
我不太懂这个，尝试删除报错的文件之后没能解决问题，并且删除的main.js文件会自动再生成QAQ

**Comment by IcedDog** [comment]
删除文件 `betterncm/plugins/actionEnhancement.plugin` 应该可以解决问题，再在新版本里重装就行

**Comment by XingYeDianXia** [comment]
> 删除文件 `betterncm/plugins/actionEnhancement.plugin` 应该可以解决问题，再在新版本里重装就行

OK，已解决，感谢大佬

**Comment by IcedDog** [comment]
> > 删除文件 `betterncm/plugins/actionEnhancement.plugin` 应该可以解决问题，再在新版本里重装就行
> 
> OK，已解决，感谢大佬

解决了记得close下issue（
