### ISSUE TITLE
main.js加载出错

### ISSUE THREAD

**Issue by Nagisa-233** [MicroCBer/BetterNCM#170]
第 1 次加载发生错误：
Error: 插件脚本 C:\Users\NanamiMao\betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20068), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18215)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at v (betterncm://betterncm/framework.js:1:20106)
    at async r (betterncm://betterncm/framework.js:1:20390)
    at v (betterncm://betterncm/framework.js:1:20174)
    at async r (betterncm://betterncm/framework.js:1:20390)

第 2 次加载发生错误：
Error: 插件脚本 C:\Users\NanamiMao\betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20068), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18215)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at v (betterncm://betterncm/framework.js:1:20106)
    at async r (betterncm://betterncm/framework.js:1:20390)
    at v (betterncm://betterncm/framework.js:1:20174)
    at async r (betterncm://betterncm/framework.js:1:20390)

第 3 次加载发生错误：
Error: 插件脚本 C:\Users\NanamiMao\betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20068), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18215)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at v (betterncm://betterncm/framework.js:1:20106)
    at async r (betterncm://betterncm/framework.js:1:20390)
    at v (betterncm://betterncm/framework.js:1:20174)
    at async r (betterncm://betterncm/framework.js:1:20390)

**Comment by Luckuy-Nicke** [comment]
<img width="150" alt="image" src="https://user-images.githubusercontent.com/99702381/210964672-97eafaf6-3850-4de6-a660-dfd7d5ebdf41.png">
在这两个文件夹中把关于actionEnhancement插件和文件删了，路径是C:\Users\NanamiMao\betterncm。
再去重载一下插件，应该就没问题了，然后再去插件市场再去下载一个。
我和你遇到的问题一样，删完重装就没事

**Comment by MicroCBer** [comment]
> <img alt="image" width="150" src="https://user-images.githubusercontent.com/99702381/210964672-97eafaf6-3850-4de6-a660-dfd7d5ebdf41.png">
> 
> 在这两个文件夹中把关于actionEnhancement插件和文件删了，路径是C:\Users\NanamiMao\betterncm。 再去重载一下插件，应该就没问题了，然后再去插件市场再去下载一个。 我和你遇到的问题一样，删完重装就没事

√ 老版本ActionEnhancement不支持新版本betterncm
