### ISSUE TITLE
进入安全模式了。。。

### ISSUE THREAD

**Issue by Mochasu123** [MicroCBer/BetterNCM#183]
第 1 次加载发生错误：
Error: 插件脚本 C:/betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20071), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18218)
    at v (betterncm://betterncm/framework.js:1:20109)
    at async r (betterncm://betterncm/framework.js:1:20393)
    at v (betterncm://betterncm/framework.js:1:20177)
    at async r (betterncm://betterncm/framework.js:1:20393)

第 2 次加载发生错误：
Error: 插件脚本 C:/betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20071), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18218)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at v (betterncm://betterncm/framework.js:1:20109)
    at async r (betterncm://betterncm/framework.js:1:20393)
    at v (betterncm://betterncm/framework.js:1:20177)
    at async r (betterncm://betterncm/framework.js:1:20393)

第 3 次加载发生错误：
Error: 插件脚本 C:/betterncm/./plugins_runtime\actionEnhancement/main.js 加载出错: TypeError: Cannot read property 'addEventListener' of null
    at EventTarget.eval (eval at v (betterncm://betterncm/framework.js:1:20071), <anonymous>:44:37)
    at EventTarget.<anonymous> (betterncm://betterncm/framework.js:1:18218)
    at EventTarget.t (https://s6.music.126.net/static_public/5e7dd9894cb30d2fd378f94f/2.12.3/music-corona.min.js:1:8627)
    at v (betterncm://betterncm/framework.js:1:20109)
    at async r (betterncm://betterncm/framework.js:1:20393)
    at v (betterncm://betterncm/framework.js:1:20177)
    at async r (betterncm://betterncm/framework.js:1:20393)

**Comment by Mochasu123** [comment]
重载了一下就好了
