### ISSUE TITLE
插件激活失败，安全模式启动

### ISSUE THREAD

**Issue by ADP-P-P** [MicroCBer/BetterNCM#186]
插件启动失败，应用内日志如下
```log
第 1 次加载发生错误：
Error: directory_iterator::directory_iterator: 系统找不到指定的路径。
    at ne (betterncm://betterncm/framework.js:1:20594)
    at betterncm://betterncm/framework.js:4:333

第 2 次加载发生错误：
Error: directory_iterator::directory_iterator: 系统找不到指定的路径。
    at ne (betterncm://betterncm/framework.js:1:20594)
    at betterncm://betterncm/framework.js:4:333

第 3 次加载发生错误：
Error: directory_iterator::directory_iterator: 系统找不到指定的路径。
    at ne (betterncm://betterncm/framework.js:1:20594)
    at betterncm://betterncm/framework.js:4:333
```
插件目录下log.log内容如下

```log
Plugin Loading Error: rename: 
Plugin Loading Error: rename: 
Plugin Loading Error: rename: 
Plugin Loading Error: rename: 
Plugin Loading Error: rename: 
Plugin Loading Error: rename: 
Plugin Loading Error: rename: 
Plugin Loading Error: rename: 
```

出现bug后多次尝试重启网易云音乐无效，错误日志均如上所示，后使用betterNCM重载插件后修复。

BetterNCM:1.0.0
网易云音乐:2.10.6(Build:200601)(Patch:1:d3fe8dd)
操作系统:Windows 11

**Comment by MicroCBer** [comment]
#183 
本来就不是让你重启的……
