### ISSUE TITLE
[ StyleSnippet-0.1.1 ] 更新后所有插件无法加载，BetterNCM自动进入安全模式

### ISSUE THREAD

**Issue by Ling-Zero** [MicroCBer/BetterNCM#288]
### Bug 描述

[ StyleSnippet-0.1.1 ] 更新后所有插件无法加载，BetterNCM自动进入安全模式

### 复现步骤

1. 更新StyleSnippet-0.1.1，重载插件
2. 看到错误

### 期望行为

指正我操作问题或者修复bug

### 屏幕截图

![image](https://user-images.githubusercontent.com/89287049/217124911-196933b0-fe3a-4202-a1f7-8bdf8146a6bb.png)

### BetterNCM 版本

1.0.1

### 网易云音乐版本

2.10.6

### 网易云音乐 Patch 版本

5ad43a6

### 已安装插件

![image](https://user-images.githubusercontent.com/89287049/217124737-78e4a264-fa0d-450f-9caf-f1c4b55f5c0a.png)

### 补充

第 1 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 9)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

第 2 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 9)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

第 3 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 9)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

第 1 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 9)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

第 2 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 9)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

第 3 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 9)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

**Comment by Ling-Zero** [comment]
这路径肯定不对，咋整

**Comment by magesep** [comment]
所以怎么解决的？
